# Stage 1: Build the Angular application
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
# Append the legacy flag to bypass peer dependency checking blocks
RUN npm install --legacy-peer-deps 
COPY . .
RUN npx ng build shared-assets --configuration production
RUN npx ng build shell --configuration production

# Stage 2: Serve the application using Nginx
FROM nginx:alpine
COPY --from=build /app/dist/shell/browser /usr/share/nginx/html
COPY nginx.shell.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
